localgov_login_page.settings:
  type: config_object
  label: 'LocalGov Login Page settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    redirect_route:
      type: string
      label: 'Redirection route'
