name: Test localgovdrupal/localgov_core drupal-module

on:
  push:
    branches:
      - '2.x'
  pull_request:
    branches:
      - '2.x'
  workflow_dispatch:

jobs:
  tests:
    uses: localgovdrupal/localgov_shared_workflows/.github/workflows/test-module.yml@fix/copy-core-prettier-config-before-testing
    with:
      project: 'localgovdrupal/localgov_core'
      project_path: 'web/modules/contrib/localgov_core'
